#!/usr/bin/ruby -s

require 'csv'

def preprocess(input)
  clean = []
  input.each do |line|
    if line.valid_encoding? then
      clean << line.rstrip
    else
      puts "BAD LINE" + line
    end
  end
  clean.join("\n")
end

class Normalize

  def initialize
  end

end

# Primitive option handling
if $h then
  puts "Usage"
  exit
end


input = ARGF.readlines
clean = preprocess(input)

# Display preprocessed data
if $p then
  puts
  puts clean
  exit
end


rows = []
CSV.parse(clean, headers: true, header_converters: :symbol) do |row|
  row = row.to_h
  row = row.each_with_object({}){ |(k,v), h| h[k.to_sym] = v }
  rows << row
end

puts
puts rows
